---
name: Deploy-Documentation

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    deploy:
        name: Deploy docs
        runs-on: ubuntu-latest
        steps:
            -   # Setup Python version
                name: Setup Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.x

            -   # Install Material for MkDocs
                name: Install Material for MkDocs
                run: pip install mkdocs-material

            -   # Git Checkout
                name: Checkout Code
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   # Build and deploy Documentation
                name: Build Docs
                run: mkdocs gh-deploy --force
